steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://ares-bucket/environments/code-server-bot", "./.env"]

  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "asia.gcr.io/archisdi-285415/code-server-bot:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args:
      ["tag", "asia.gcr.io/archisdi-285415/code-server-bot:$SHORT_SHA", "asia.gcr.io/archisdi-285415/code-server-bot:latest"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/archisdi-285415/code-server-bot:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/archisdi-285415/code-server-bot:latest"]

  - name: "gcr.io/cloud-builders/gke-deploy:stable"
    args:
      - run
      - --filename=deployment.yaml
      - --image=asia.gcr.io/archisdi-285415/code-server-bot:latest
      - --location=asia-southeast2-a
      - --cluster=ares-01-cluster